# Custom Language File for Launcher Customizer

[ejs.app]
title = "DreamForge-Games Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/DreamForgeGames/DreamForgeGames-Launcher"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/BduaqWFaPH"

[ejs.settings]
sourceGithubLink = "https://github.com/DreamForgeGames/DreamForgeGames-Launcher"
supportLink = "https://github.com/DreamForgeGames/DreamForgeGames-Launcher/Issues"

[ejs.welcome]
welcomeHeader = "WELCOME TO DREAMFORGE GAMES"
welcomeDescription = "With this launcher using our Games is made easy"
welcomeDescCTA = "You are just a few clicks away."
