# Custom Language File for Launcher Customizer

[ejs.app]
title = "DreamForge-Games Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/DreamForgeGames/DreamForge-Launcher"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/BduaqWFaPH"

[ejs.settings]
sourceGithubLink = "https://github.com/DreamForgeGames/DreamForge-Launcher"
supportLink = "https://github.com/DreamForgeGames/DreamForge-Launcher/Issues"

[ejs.welcome]
welcomeHeader = "WELCOME TO DREAMFORGE GAMES"
welcomeDescription = "lorem"
welcomeDescCTA = "You are just a few clicks away."
