# Custom Language File for Launcher Customizer

[ejs.app]
title = "DreamForgeGames Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/DreamForgeGames/DreamForgeGames-Launcher"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/BduaqWFaPH"

[ejs.settings]
sourceGithubLink = "https://github.com/DreamForgeGames/DreamForgeGames-Launcher"
supportLink = "https://github.com/DreamForgeGames/DreamForgeGames-Launcher/issues"

[ejs.welcome]
welcomeHeader = "Welcome to DreamForge Games"
welcomeDescription = ""
welcomeDescCTA = "You are just a few clicks away."
